### ISSUE TITLE
Feature request: multiple sources

### ISSUE THREAD

**Issue by cybershambles** [tests-always-included/mo#12]
hey, I'd love to have two sources that overwrite values in the order they are given.

mo --source=globals,notglobals files

bob=1 in globals and bob=2 in notglobals will generate the output with 2
bob=1 in globals and nothing in notglobals will generate the output with 1

**Comment by fidian** [comment]
First off, thank you for reporting this issue.  I completely thought this would work, so I started to construct this scenario and found, to my amazement, that this was not working.  The commit ecfc973 fixes the problem that was found.  Now it works as expected.

![image](https://cloud.githubusercontent.com/assets/428348/21352313/970a74dc-c686-11e6-8ef3-b6fada01d1cb.png)

Does that work for you as well with the latest commit?

**Comment by fidian** [comment]
I'm going to close this issue.  If you still experience problems, feel free to reopen it or create a new task.

I'm glad that you tried out `mo` and reported this issue!

**Comment by cybershambles** [comment]
Wow. Thanks for the prompt response.
