### ISSUE TITLE
Indentation of partial directly after if is incorrect

### ISSUE THREAD

**Issue by jakeheis** [tests-always-included/mo#19]
When including a partial directly after an if statement, only the first line is correctly indented.

`template`:
```
lines:
  {{#include}}
  {{> partial.yml }}
  {{/include}}
key: value
```
`partial`:
```
- first line
- second line
```

When `include="true"`:

Expected:
```
lines:
  - first line
  - second line
key: value
```

Got:
```
lines:
  - first line
- second line
key: value
```

I'm working around this currently by adding a comment between the if statement and the partial:

`template`:
```
lines:
  {{#include}}
  # Fixes indentation
  {{> partial.yml }}
  {{/include}}
key: value
```
Output (which is correct):
```
lines:
  # Fixes indentation
  - first line
  - second line
key: value
```

**Comment by fidian** [comment]
I've just pushed some changes that should close this issue. Would you take a look and see if those changes also work for you?

**Comment by jakeheis** [comment]
That fixes the issue, thanks so much!
