### ISSUE TITLE
Negative indices for substrings are not allowed

### ISSUE THREAD

**Issue by fidian** [tests-always-included/mo#2]
Older versions of bash don't allow `${STRING:0:-1}` syntax.  See https://gist.github.com/rk295/a2a48c3b0f8d753df101

**Comment by fidian** [comment]
Adding @rk295 to this issue so he knows when it gets resolved.

**Comment by rk295** [comment]
Bash 4.2 only according to http://tldp.org/LDP/abs/html/bashver4.html#NEGOFFSET

**Comment by fidian** [comment]
Negative indices have been removed.
