### ISSUE TITLE
Create a Release

### ISSUE THREAD

**Issue by dagrooms52** [tests-always-included/mo#20]
Is it possible you could create a release for the project so that I could pull just a specific version? Right now I'm doing `curl -sSO https://raw.githubusercontent.com/tests-always-included/mo/master/mo` as suggested. I really don't want to leave it this way because when my container hits production, any change to this project would slide into my project unnoticed, potentially breaking it.

I wanted to add that I love the project, it's really useful and having pure bash is a huge plus! 👍

**Comment by dagrooms52** [comment]
I should add GitHub's guide to creating releases: https://help.github.com/articles/creating-releases/
It looks super simple!

**Comment by fidian** [comment]
You're absolutely right, there should be a released version.

https://github.com/tests-always-included/mo/releases/tag/1.0.0
