### ISSUE TITLE
Feature request:  Nicer iterators & partials

### ISSUE THREAD

**Issue by sc0ttj** [tests-always-included/mo#28]
#### 1. Nicer iterators

First, here is the custom iterator I am using for hashes in arrays:

```shell
# ITEMS():  A custom mustache iterator called ITEMS:
#           Uses special keywords ITEMS and ITEM.
#
# Usage:
#
# Set an array of hashes, which must be called ITEMS:
#
#   declare -A archive=([url]="archive.html" [name]="Archive page")
#   declare -A contact=([url]="contact.html" [name]="Contact page")
#   ITEMS=(archive contact)
#
# You can then use nested array data in your mustache templates like so:
#
#   {{#ITEMS}}
#     {{ITEM.name}} is at {{ITEM.url}}
#   {{/ITEMS}}
#
# Finally, build the output like so:
#
#   cat path/to/some-file.mustache | mo > some-file.html
#
function ITEMS {
  # The block contents come in through standard input. Capture it here.
  local content="$(cat)"
  local length=${#ITEMS[@]}
  local i=0
  # Get list of items
  for ITEM in "${ITEMS[@]}"; do
    # String replace ITEM_ with the name
    # This changes everything in the content block of the template.
    # It rewrites {{ITEM.name}} into {{foo.name}}, for example - where
    # 'foo' is a hash with they key 'name'.
    # You can prefix your environment variables and do other things as well.
    echo -ne "$content" | sed "s/{{ITEM/{{${ITEM}/g"
    i=$(($i + 1))
    # if not last item in array, add comma
    if [ "$AUTO_APPEND" != '' ];then
      [ "$i" != "$length" ] && echo "$AUTO_APPEND" || echo ''
    fi
  done
}
# export the function so `mo` can use it
export -f ITEMS
```

I'd love to be able to define the array and variable names used by my custom iterator **as a param for that iterator**, so that I can make my code nicer... I'd like to rename my `ITEMS` iterator to `{{#foreach}}`, and use it like so:

```handlebars
{{#foreach link in links}}
  <a href="{{link.url}}">{{link.name}}</a>
{{/foreach}}
```
^ **where `links` is the array of hashes I want to iterate over**.

..I've been unable to update my `ITEMS` function to achieve this, would really, really love some help.

I'd also love for this iterator to provide various vars "for free" when inside the iteration body, such as `{{#odd}}`, `{{#even}}`, `{{#first}}`, `{{#last}}`, `{{index}}`, which could be used like so:

```handlebars
{{#foreach link in links}}
  <a href="{{link.url}}">{{link.name}}</a>{{^last}},{{/last}}
{{/foreach}}
```
^ obviously, this would append a comma after each link, except the last one...

..a 'custom' iterator that worked in that way would be nice enough to include in mo by default, as a `{{#foreach}}` operator/iterator.

The benefit of this is obviously that users of `mo` will no longer need to laboriously scaffold out some helper function to do thier looping stuff.. They simply define the array (or array of hashes) and pass it in as a paramater... Soooo much easier.

#### 2. A global partial dir:

Partials seem not to work very well for me.. I think having an env var set like `$MO_PARTIAL_DIR` would be great - cos mo struggles to find the partials without defining full paths when used in more complex programs.. "Complex" means they may have scripts that live in different dirs, away from mo itself, outside of `$PATH`, changing `$PWD` a lot, etc..

Can mo be made to use a `$MO_PARTIAL_DIR` env var, so that templates can be made as below, and will work:

```handlebars
{{>my_file}}
```
^ should work regardless of where `mo` is lives, or is called from, or where the template lives... the file `my_file` could actually be at `${MO_PARTIAL_DIR}/myfile[.mustache]`..

#### 3. Partials with params:

Does the following (or something similar) work in mo? ..

```handlebars
{{>some_partial
  param1="one"
  param2=2
  param3="$some_shell_var"
  param4="{{some_var_or_func}}"
}}
```

...I have some snippets lying around which nearly make it work with params as strings, but it's not working yet, and I didn't actually test mo itself to see if the above, or something similar, is supported..

Thanks.

**Comment by fidian** [comment]
I've split this into separate issues. Having too many details in a single issue makes it really difficult to track and it can't be closed or show any partial progress until everything is done.
