### ISSUE TITLE
multiple `--source` command line options

### ISSUE THREAD

**Issue by tbussmann** [tests-always-included/mo#42]
Sometimes it would be useful to be able to specify `-s=` multiple times for one `mo` command. Like if you use some global and local override definitions or if you want to provide one file defining an environment with reusable functions and one defining the variables for the execution. Currently the option seems to be allowed only once. 

As a workaround you can source one file within the other, there are use-cases where one want to avoid any boilerplate code within the file.

**Comment by fidian** [comment]
I've just written a test to confirm this behavior exists. You may use `-s` or `--source` multiple times and each file will be sourced. If the variables override each other, the one defined last wins.

**Comment by fidian** [comment]
Closing because the feature request was already implemented. I've added comments in the documentation and an additional test to make sure it will be around in the future.
