### ISSUE TITLE
associative array workaround

### ISSUE THREAD

**Issue by patjlm** [tests-always-included/mo#5]
Hello,
Would it be possible to workaround the associative array question with templates like: 
```bash
#!/bin/bash

cd "$(dirname "$0")" # Go to the script's directory

export PREFIX_ARRAY=( P1 P2 )
export P1_NAME=p1name
export P1_VALUE=p1value
export P2_NAME=p2name
export P2_VALUE=p2value

cat << EOF | . ../mo
Here are the items in the array:
{{#PREFIX_ARRAY}}
  {{.}}:
    * name: {{_NAME}}
    * value: {{_VALUE}}
{{/PREFIX_ARRAY}}
EOF
```

This would mean that {{_NAME}} would trigger a lookup for ${P1_NAME} and fallback to ${_NAME}

**Comment by fidian** [comment]
This does not appear to be standard mustache format and I would not expect this to work with other parsers.  Mo is trying to implement the spec.  I would also have a hard time determining if _NAME is supposed to be prefixed or not and with effectively double-parsing the template.  Syntax like `{{{{.}}_NAME}}` might be preferable, yet it looks ugly.

That said, there does appear to be an issue with associative arrays.  The following should work, but does not.  I will file that one with a separate bug report because it's different than your request.

```
#!/bin/bash

declare -A DATA
DATA=([one]=111 [two]=222)

cat <<EOF | . ~/bin/mo
Accessing data directly:
    DATA:  {{DATA}}
    One: {{DATA.one}}
    Two: {{DATA.two}}

Things in DATA:
{{#DATA}}
    Item: {{.}}
{{/DATA}}
EOF
```

If the above associative arrays worked as expected, would your issues be resolved?

**Comment by patjlm** [comment]
I understand and agree it does not match the mustache specs.

However, I am not sure the (valid) implementation you propose would solve the need.

I am basically trying to use the "non-empty list" feature of the mustache spec https://mustache.github.io/mustache.5.html : 

Template:
```
{{#repo}}
  <b>{{name}}</b>
{{/repo}}
```
Hash:
```
{
  "repo": [
    { "name": "resque" },
    { "name": "hub" },
    { "name": "rip" }
  ]
}
```

How would this hash be best represented in bash (i am for from being expert in bash...) ?

**Comment by patjlm** [comment]
no, the idea is to deal with any number of property.
Indeed, the example in the mustache doc mentions only one. But it is meant to work with any.

**Comment by fidian** [comment]
Did you inspect the new file that I committed to the repository?  It uses
two properties and can easily be expanded to any number of properties.

**Comment by fidian** [comment]
Another idea would be to use another mustache parser and supply the data in
JSON or another format that the other parser understands.  For instance,
the JavaScript version can be supplied any JSON data and sets of templates
to parse.

**Comment by patjlm** [comment]
I did check the example file you commited. I'd say it looks a bit hacky but could do the trick.
I'd really like to stick with bash and avoid any other dependency.
Is it possible to have arrays of arrays in bash ?
Something like:
```
repo=(([name]=resque [url]=resque.com) ([name]=hub [url]=hub.com) ([name]=rip [url]=rip.com))
```

**Comment by fidian** [comment]
You are not able to have arrays of arrays in Bash, so the hackish solution
I presented is really your only option if you stick with Bash.

It is possible to roll your own multidimensional arrays in Bash but that's
certainly well beyond the scope of this issue and it's a non-trivial thing
to implement properly.  You can also use hash files or ini files, but those
would also take custom functions.  If you need multidimensional arrays I
would strongly suggest looking at a scripting language like python or perl
as it is often installed by default on many systems.

--
Tyler Akins

**Comment by patjlm** [comment]
Thanks a lot for your feedback and patience.
I'll try to use something like the example script you committed.
You may want to add a comment about incomplete support of mustache "non-empty list" in mo's readme.md.
Also, following your fix of #6, I guess you can remove this item in the 'mustache syntax' concession section:
```
Dotted names are not supported and this means associative arrays are not addressable via their index.
Partly this is because our target (Bash 3) does not support associative arrays.
```
Cheers

**Comment by fidian** [comment]
You're totally right that I need to update the documentation.

Could you explain a bit more about incomplete support of the non-empty
list?  I pass the tests in the spec so I don't quite get what you are
asking.

--
Tyler Akins

**Comment by patjlm** [comment]
As I understand it, mo does not support full non-empty list section as described in corresponding section in the [doc](https://mustache.github.io/mustache.5.html) and as the example in https://github.com/tests-always-included/mo/issues/5#issuecomment-99167244 shows. This is due to bash limitations concerning array of associative arrays.
As described in your example script, the proposed workaround is to use mustache's lambda support in mo.

**Comment by fidian** [comment]
As I read it, the non-empty list section says that you can iterate over a
list.  If empty you will get nothing.  If the list is not empty, {{.}} will
refer to the current value and constructs like {{name}} would use the
current object's name property.  As Bash does not support objects, I
believe that this is not something that can be supported.

Non-empty lists do work, as seen in the associative-arrays demo file.  It's
just that you can't store objects as array values, which is documented
already:  *Bash does not support nested structures like fancy objects. The
best you can do are arrays. I'm not able to add super complex structures to
bash - it's just a shell after all!*

I will update the documentation to hopefully make this more clear.

--
Tyler Akins

**Comment by patjlm** [comment]
Sounds good! thanks!

**Comment by fidian** [comment]
Closing this issue because I don't think anything else is left to do.  If I have this wrong, please feel free to open a new issue.
