### ISSUE TITLE
Feature: Key and Index Accessors Inside Loops

### ISSUE THREAD

**Issue by Swivelgames** [tests-always-included/mo#56]
### Feature

Presently, it's possible to output the `value` of current loop context, but it's not possible to output the `key`.

The proposal would add both `{{@index}}` and `{{@key}}` as possible cases.

### Justificaton

- **Does this functionality exist in the _official_ Mustache implementation?**
  - _NO_
- **Does this functionality exist in _other_ Mustache implementations?**
  - _NO_. Only in expanded Mustache implementations.
- **Does this functionality introduce Logical constructs into this implementation's Mustache syntax?**
  - _NO_. This deals solely with data accessors.
- **Is there precedence for something like this in `mo` or another implementation?**
  - _YES_

While this feature doesn't add logic constructs, it does exist in Handlebars.js, an off-shoot of Mustache. It's important to note that Handlebars.js is not faithful to Mustache's definition of being Logic-less.

However, `mo` is already forwards-compatible with Associative Arrays in Bash, including in some advanced-aspects like the form of dot-notation that `mo` supports. None of the aforementioned are considered Logical operations. These are just data accessors.

Additionally, the keys in an associative array are often useful to Bash users. Without this, the keys iterating over an associative array are inaccessible and useless to template writers.

### Implementation Considerations

Because of the way `mo` is implemented, the addition of this is minimal, since the key is already maintained within `$moCurrent`.

- `@key` would output `foo` if `$moCurrent` is `"foo"`
- `@key` would output `bar` if `$moCurrent` is `"DATA.bar"`
- `@key` would output `2` if `$moCurrent` is `"DATA.2"`
- `@index` would output `2` if `$moCurrent` is `"DATA.2"`

**Comment by Swivelgames** [comment]
**UPDATE** Just tested this with Bash 3.1 and Bash 3.2 and `mo` executed successfully!

Just like the other Associative Array features already in `mo`, these features are compatible with Bash 4.0-5.1.

This was implemented successfully in #57

**Comment by fidian** [comment]
Everything looks good in #57, but I would like two changes.

First, I think `@key` and `@index` appear to do the same thing. I'm not really seeing a difference between them except `@index` appears to filter out non-numerics. Can their logics be combined? Is there an advantage to keeping them separate?

Secondly, please update `README.md` with the important details and possibly include it in an example. I'm thinking you could add an "Enhancements" section right before "Concessions", then briefly detail how it works and possibly link to a demo if the example starts to get long.

**Comment by Swivelgames** [comment]
@fidian Done!
