### ISSUE TITLE
(Close Pending #62) Parity: Looping a List of Associative Arrays

### ISSUE THREAD

**Issue by Swivelgames** [tests-always-included/mo#58]
### Feature

In order to bring parity with `mo` and traditional `mustache` implementations, this feature will extract the keys of an associative array when looping. This feature alone will enable `mo` to work with meaningful data structures and elevates it to a proper Mustache implementation. 

Specifically, derived from the [official documentation](https://mustache.github.io/mustache.5.html) (_See "Non-Empty Lists"_):
```bash
declare -a navItems nonFunctional
declare -A homeLink otherLink

homeLink[title]="Home"
homeLink[url]="https://www.example.com/home"

otherLink[title]="Other Link"
otherLink[url]="https://www.example.com/other-page"

navItems=(homeLink otherLink) # <- List of arrays
stringArray=("homeLink" "otherLink") # <- List of strings
```

Template:
```handlebars
# Links
{{#navItems}}
- [{{title}}]({{url}})
{{/navItems}}

# Standard List
{{#stringArray}}
- {{.}}
{{/stringArray}}
```
Output:
```markdown
# Links
- [Home](https://www.example.com/home)
- [Other Link](https://www.example.com/other-page)

# Standard List
- homeLink
- otherLink
```

### Justificaton

- **Does this functionality exist in the _official_ Mustache implementation?**
  - [_YES_](https://mustache.github.io/mustache.5.html)
- **Does this functionality exist in _other_ Mustache implementations?**
  - _YES_. Most, if not all of the others.
- **Does this functionality introduce Logical constructs into this implementation's Mustache syntax?**
  - _NO_. This deals solely with data accessors. This is officially supported by Mustache and is an expected feature.
- **Is there precedence for something like this in `mo` or another implementation?**
  - _YES_. `mo` currently supports iterating over traditional List arrays, as well as associative Arrays. And, Bash officially supports Lists of Associative Arrays. Additionally, `mo` already extracts variables into upper scopes, which can be leveraged to elevate keys of Associative Arrays into loop scopes.

### Implementation Considerations

Bash has [supported nested arrays since Bash 4.3](https://stackoverflow.com/a/44831174/253870). Because of the way that `Bash` is implemented, this addition can leverage built-in loops to iterate over Lists and extract fields from their Associative Array members.

- A list that contains Associative Arrays will extract the keys into the upper scope while looping
- After the loop completes, the extracted fields should be cleaned

**Comment by Swivelgames** [comment]
**UPDATE** Just tested this with Bash 3.1 and Bash 3.2 and `mo` executed successfully!

Just like the other Associative Array features already in `mo`, these features are compatible with Bash 4.0-5.1.

This was implemented successfully in #59

**Comment by fidian** [comment]
I'd like to propose some use cases to use as examples. For both of these I included `{{INDIRECT variableName [key]}}` indicating I wanted to get a variable or I wanted to get a specific key from a variable. Syntax here isn't important - just the idea that the information is needed.

```
. ./mo

# Use case 1: look up values in an associative array
declare -A employee
employee[123]="Tyler"
employee[456]="Joseph"
employees=(123 456)

cat <<EOF | mo
Employee list:
{{#employees}}
    - {{INDIRECT employee .}}
{{/employees}}
EOF

# Use case 2: look up another variable for internationalization
welcomeMessage="Gruß dich!"
farewellMessage="Bis spater"
messages=(welcomeMessage farewellMessage)

cat <<EOF | mo
List of messages:
{{#messages}}
* {{INDIRECT .}}
{{/messages}}
EOF

# Use case 3, getting related information
declare -A pages urls
pages["home"]="Home page"
urls["home"]="http://localhost/"
pages["search"]="Search for content"
urls["search"]="http://localhost/search/"

cat <<EOF | mo
Pages on the site:
{{#pages}}
* [{{.}}]({{INDIRECT urls @key}})
{{/pages}}
EOF
```

Hopefully this explains some of the ways I've seen the templating system get used. Normally a function is created to do the work, but having a general purpose mechanism in place would be ideal. Getting function arguments parsed and supporting some sort of generic indirect syntax (perhaps steal from C's use of `*variable` or PHP's use of `$$variable`.

**Comment by fidian** [comment]
I think that #62 solved this problem, though in a different way. Would you concur?
