### ISSUE TITLE
Cannot reference global varibales within a loop

### ISSUE THREAD

**Issue by schneidexe** [tests-always-included/mo#7]
I wrote this sample code:

```
#!/bin/bash

STR=abc
DATA=(111 222)

cat <<EOF | . ./mo
{{STR}}
{{#DATA}}
    Item: {{.}}
    String: {{STR}}
{{/DATA}}
EOF
```

Which prints:
```
abc
    Item: 111
    String: 111
    Item: 222
    String: 222
```

When is use {{STR}} instead of printing the content of the global var STR it prints the current item like I would use {{.}}.

**Comment by fidian** [comment]
I've found and fixed the bug and will push it (with tests) to GitHub in a few minutes.  Thank you for helping me out and reporting this issue!

**Comment by fidian** [comment]
I've included your example as a test case to ensure things are working as expected.

**Comment by schneidexe** [comment]
Cool! Thanks for the quick fix. We're using mo a lot around here... :)
