### ISSUE TITLE
Slow parsing of template since upgrade from 2.2.0 to current version

### ISSUE THREAD

**Issue by JuergenMang** [tests-always-included/mo#71]
Hello,

first: great work!

I use this project to parse a template with ~2000 lines. I implemented it originally with the 2.2.0 version of this project. After upgrading to the current version, the parsing is much slower. It seems this is a similar issue as #69.

Attached is a obfuscated template.

[template.json](https://github.com/tests-always-included/mo/files/14721003/template.json)

**Comment by cogito-ray** [comment]
I am having the same issue with slowness. I had to upgrade from 2.2 to 3 because I needed to use --allow-function-arguments which was not working as expected in 2.2.  It worked fine in 3.  I use mo to process a bunch of templates in automation - all processing uses the same input file and the typical render time is usually seconds but sub 20 seconds. The only delta is the template file.  Now some files take longer than others. 

File size (bytes) -> Render time (minutes:seconds)

22212 -> 02:33
12876 -> 00:09 
10110 -> 00:17
36411 -> 13:51

Those are my 4 largest template files.

When I moved from 2.2 to 3 I created a wrapper to mo to execute mo with the allow-function-arguments. See below.  If I have some more time I will try to further analyze my templates, their sizes and possibly do some bench marking with 2.2 and 3.0.  I'll instrument my code to gather some timing and try to report back.

`#!/bin/bash
# this is a wrapper for the mo bash template engine

# Function to iterate over array of array (can't use associative array but this works out fine)
# this function is used within a template and needs to be defined before we source the mo engine

foreach() {
    # Trying to use unique names
    local foreachSourceName foreachIterator foreachEvalString foreachContent

    foreachContent=$(cat)

    local x
    x=("${@}")
    if [[ "$2" != "as" && "$2" != "in" ]]; then
        echo "Invalid foreach - bad format."
    elif [[ "$(declare -p "$1")" != "declare -"[aA]* ]]; then
        : # echo "$1 is not an array"
    else
        foreachSourceName="${1}[@]"

        for foreachIterator in "${!foreachSourceName}"; do
            foreachEvalString=$(declare -p "$foreachIterator")
            foreachEvalString="declare -a $3=${foreachEvalString#*=}"
            eval "$foreachEvalString"
            echo "$foreachContent" | mo
        done
    fi
}

# source mo in order to support function arguments
. ./scripts/mo

# invoke mo with function arguments
mo --allow-function-arguments "$@"`

**Comment by cogito-ray** [comment]
Here is some profiling data - elapsed time and size for various templates that we process.  The template name has been hashed.  It is an sdiff - left is mo3 and right is mo2.2.  I plan to start using the various different versions of mo to see if I can identify when the problem started.

ee34998a179cce956ee75672682a392f17c38aab15c656f79004f30e61de2c8c 00:00:00 1429    ee34998a179cce956ee75672682a392f17c38aab15c656f79004f30e61de2c8c 00:00:00 1429
d2398912a3711ab71241cafac2772a746a2232af74fc257e60de5a1448cfd4f9 00:00:00 1048  | d2398912a3711ab71241cafac2772a746a2232af74fc257e60de5a1448cfd4f9 00:00:01 1048
98db4a2e32778d1b019eabe9c3fb6d617a0139af897d273d1200503194309760 00:00:01 2831  | 98db4a2e32778d1b019eabe9c3fb6d617a0139af897d273d1200503194309760 00:00:00 2831
4b24233c8b37773f2b5deb931ad1ffff4180fb67c6a214bec4a52d6d7b5366c4 00:00:01 1559  | 4b24233c8b37773f2b5deb931ad1ffff4180fb67c6a214bec4a52d6d7b5366c4 00:00:00 1559
1427eb04a76470acb88fa4376f1e1bcbe1a3c72b2043cb2c6000dcb8f19a3cb2 00:00:10 12876 | 1427eb04a76470acb88fa4376f1e1bcbe1a3c72b2043cb2c6000dcb8f19a3cb2 00:00:01 12876
16694d2c9341f25b2be79c45eac2a8cb34b90b57734822ec961466d9dcc2d907 00:00:01 4685  | 16694d2c9341f25b2be79c45eac2a8cb34b90b57734822ec961466d9dcc2d907 00:00:00 4685
631d3f709057957761b1ae8cda4459ce6a8d82fc07388701f9fbdde7413d332f 00:00:01 5000    631d3f709057957761b1ae8cda4459ce6a8d82fc07388701f9fbdde7413d332f 00:00:01 5000
e45cfd9dcb7f0d36727b1539d8d2b2cf0fc8b43ff7cad86c397f76f7b4c89166 00:02:02 22212 | e45cfd9dcb7f0d36727b1539d8d2b2cf0fc8b43ff7cad86c397f76f7b4c89166 00:00:03 22212
314f9f4924bbee9cd760db6f3bd5afa739b767a7c90dcfee792fd15967998fdc 00:00:00 302     314f9f4924bbee9cd760db6f3bd5afa739b767a7c90dcfee792fd15967998fdc 00:00:00 302
b08fae1d7e8a98fabb1f0825594cb6df5fcac9c33b7b8ad0c60842b450b493ca 00:00:00 1145    b08fae1d7e8a98fabb1f0825594cb6df5fcac9c33b7b8ad0c60842b450b493ca 00:00:00 1145
a14bffd8683d378ac5712d18556a3d1ea73ca7e3ae759a0f8b562af842717c2a 00:00:00 1130    a14bffd8683d378ac5712d18556a3d1ea73ca7e3ae759a0f8b562af842717c2a 00:00:00 1130
11a7c0754f0971bec09d9c527dc369bbdb09ffd6d99c9d52946f269418fe3197 00:00:00 301     11a7c0754f0971bec09d9c527dc369bbdb09ffd6d99c9d52946f269418fe3197 00:00:00 301
1a841f5abedcdb6238ef6cbe563a4ffa95ddd98c5a68c9563b10ec4aaee9a043 00:00:01 1125  | 1a841f5abedcdb6238ef6cbe563a4ffa95ddd98c5a68c9563b10ec4aaee9a043 00:00:00 1125
cb05d50308449180a66475bc857c73cf1b16746379a2e6d17ca3b1708a6ec41f 00:00:00 1127    cb05d50308449180a66475bc857c73cf1b16746379a2e6d17ca3b1708a6ec41f 00:00:00 1127
9ee3f540ab820df103b0f2808fb93d3fb4605d73041b0ec3eb2a845b5a01c500 00:00:00 565     9ee3f540ab820df103b0f2808fb93d3fb4605d73041b0ec3eb2a845b5a01c500 00:00:00 565
dba1dcfbde8c66d61b41e56bec04264443dda22e1b83a3d6b452459f321c8502 00:00:01 1162    dba1dcfbde8c66d61b41e56bec04264443dda22e1b83a3d6b452459f321c8502 00:00:01 1162
3d369a71d78ebfb262d5a406dde034bf5bba56552e4f0fa3f26adae61bb19fb4 00:00:15 10110 | 3d369a71d78ebfb262d5a406dde034bf5bba56552e4f0fa3f26adae61bb19fb4 00:00:01 10110
ed9f96c032a10dd0f432b198bbe74c369c4574adeca92a787d140c8b27ca3aea 00:00:01 1492  | ed9f96c032a10dd0f432b198bbe74c369c4574adeca92a787d140c8b27ca3aea 00:00:00 1492
86552d567eaafb135de499598d121a2371c53f2e4bf524f61227f511a64cd44c 00:00:00 961   | 86552d567eaafb135de499598d121a2371c53f2e4bf524f61227f511a64cd44c 00:00:01 961
6e573811b8587c3cabe45e543da797fa21bbd601078d93850de192a029fdc288 00:00:05 5603  | 6e573811b8587c3cabe45e543da797fa21bbd601078d93850de192a029fdc288 00:00:00 5603
126ab4c11be5b5504435cd49e00513be1b6cb05ce704d0b11edb1e6428ed3803 00:00:00 1013  | 126ab4c11be5b5504435cd49e00513be1b6cb05ce704d0b11edb1e6428ed3803 00:00:01 1013
687b1dd5a113d649337ddad3eb1fa837b4fede773e91f950656e0eb433376982 00:00:00 1028    687b1dd5a113d649337ddad3eb1fa837b4fede773e91f950656e0eb433376982 00:00:00 1028
ce9d90adb7e3bc529e29e9c5b34f858fd66645da2f8b80d8ab0d26fb1fcb8bdf 00:00:01 1219  | ce9d90adb7e3bc529e29e9c5b34f858fd66645da2f8b80d8ab0d26fb1fcb8bdf 00:00:00 1219
268264fff680d017434e7e2896fff22d2ace36233b033e6ba78a0cbe88533972 00:00:00 1000    268264fff680d017434e7e2896fff22d2ace36233b033e6ba78a0cbe88533972 00:00:00 1000
704fe72a9e4a5fcf35382101e1e0af743aef546e0c54f90d7501e66a32848853 00:00:00 1013    704fe72a9e4a5fcf35382101e1e0af743aef546e0c54f90d7501e66a32848853 00:00:00 1013
682705aad2b10aed6ba0e5be28f27c61c5ddeabbfe8f21b8150eba73f90edf45 00:00:00 1013  | 682705aad2b10aed6ba0e5be28f27c61c5ddeabbfe8f21b8150eba73f90edf45 00:00:01 1013
4073dd165a3e403a8a255264070a15df3278059986a1af4183af88c7d238b646 00:00:01 1043  | 4073dd165a3e403a8a255264070a15df3278059986a1af4183af88c7d238b646 00:00:00 1043
16921ee225e8247dd1fea06e9f199de216223fae69f70b2d8393786bfd8cd413 00:00:00 1361    16921ee225e8247dd1fea06e9f199de216223fae69f70b2d8393786bfd8cd413 00:00:00 1361
a3a131f022942167088fbc12035c8f6f87fb8a870fafce05e0a5cf2af4d8a2c9 00:00:00 1513  | a3a131f022942167088fbc12035c8f6f87fb8a870fafce05e0a5cf2af4d8a2c9 00:00:01 1513
14eef037a98574c7a1fdbbad029ef25e84199881d6e2cdc6c3e6571187003688 00:00:00 1061    14eef037a98574c7a1fdbbad029ef25e84199881d6e2cdc6c3e6571187003688 00:00:00 1061
0bbf5cf1304d1f0b8f58c78dece8fd8796633cf6f3336eb003dabd30c70f00cf 00:00:05 6325  | 0bbf5cf1304d1f0b8f58c78dece8fd8796633cf6f3336eb003dabd30c70f00cf 00:00:01 6325
b7ef6fa7bc35fe15b35816454f707fe542e650d7faee57830baa7d3cc0a232bf 00:00:02 8805  | b7ef6fa7bc35fe15b35816454f707fe542e650d7faee57830baa7d3cc0a232bf 00:00:00 8805
529cc59ef963341a29d0c68bb8ce9f759876e2b43ec506d49ba3a871cda9ed9e 00:00:00 1938    529cc59ef963341a29d0c68bb8ce9f759876e2b43ec506d49ba3a871cda9ed9e 00:00:00 1938
6d796c091ad970cf681ffa76c968ac691739d206ca0653bedb84c10bb0cf10f2 00:00:00 442     6d796c091ad970cf681ffa76c968ac691739d206ca0653bedb84c10bb0cf10f2 00:00:00 442
459d03cbe45ccbf18f0267918fc7732d21ad262c4030137593bad5e464b5c852 00:00:01 1415    459d03cbe45ccbf18f0267918fc7732d21ad262c4030137593bad5e464b5c852 00:00:01 1415
1bb69883c003207b1020349ab82a183b5d658ed427e74e8df2d7bee8f5332be6 00:00:00 2517    1bb69883c003207b1020349ab82a183b5d658ed427e74e8df2d7bee8f5332be6 00:00:00 2517
6ba007f007d2ae223c1c583a8d9a3f467e605b770578b564e7a48caef72713bc 00:00:02 2646  | 6ba007f007d2ae223c1c583a8d9a3f467e605b770578b564e7a48caef72713bc 00:00:00 2646
58d890bfd73deb509ed075c8073f70d1e8ad3b0dfdee9901cc89bb6cf50aed44 00:00:00 739   | 58d890bfd73deb509ed075c8073f70d1e8ad3b0dfdee9901cc89bb6cf50aed44 00:00:01 739
3836a4a43d5aabc32817d594ca31d17bab4a26d170401aa756155227b99e57cf 00:00:00 1648    3836a4a43d5aabc32817d594ca31d17bab4a26d170401aa756155227b99e57cf 00:00:00 1648
49940172a20d2ca681c954209b63a92db5daadca973a207b6ab26599c593109e 00:00:03 4653  | 49940172a20d2ca681c954209b63a92db5daadca973a207b6ab26599c593109e 00:00:01 4653
4fcca2ecc599fc4132ccec2f70bfba3460f876ba59d9622555a04ae4a7703c74 00:00:00 1343    4fcca2ecc599fc4132ccec2f70bfba3460f876ba59d9622555a04ae4a7703c74 00:00:00 1343
169d40d53fde311ee0948b65589f9d503fe0bdcdbf090ca25e8f1086e5046167 00:00:01 1343  | 169d40d53fde311ee0948b65589f9d503fe0bdcdbf090ca25e8f1086e5046167 00:00:00 1343
4d163b112a99b0e22545024e8cb1bbc4cb26ab2fd86ab218f5fbed71c6aab74f 00:00:00 1275    4d163b112a99b0e22545024e8cb1bbc4cb26ab2fd86ab218f5fbed71c6aab74f 00:00:00 1275
abfb8125cb49269ea0c2799ef442540e6599206c91bd15414fa7b4a634439892 00:00:00 740     abfb8125cb49269ea0c2799ef442540e6599206c91bd15414fa7b4a634439892 00:00:00 740
ef331187f56e4298ad100135be8ca1435f5bae2560cdfa2d0383e185ab94a90b 00:00:00 2369    ef331187f56e4298ad100135be8ca1435f5bae2560cdfa2d0383e185ab94a90b 00:00:00 2369
c0c553405cc5887b1f875a2607152d477e3b58552071f9cb237740645a274496 00:00:01 961     c0c553405cc5887b1f875a2607152d477e3b58552071f9cb237740645a274496 00:00:01 961
90faa5cd43b718dd6df09b967ca2b289061224c134ed39347c1e3a8738a0ef06 00:00:00 1261    90faa5cd43b718dd6df09b967ca2b289061224c134ed39347c1e3a8738a0ef06 00:00:00 1261
04031fb92d7de337b3f57becce3e0476bedefc6920abba6f0a48c098298d7549 00:00:02 3631  | 04031fb92d7de337b3f57becce3e0476bedefc6920abba6f0a48c098298d7549 00:00:01 3631
7751af51f1a569d3cce07811a9b6e84aedef386bd0db84a8bf67da0002457758 00:00:00 1103    7751af51f1a569d3cce07811a9b6e84aedef386bd0db84a8bf67da0002457758 00:00:00 1103
0c12998e69f5c6c645fcbb4e3172b83702940893f372589bf3d761be192070b0 00:00:01 1529  | 0c12998e69f5c6c645fcbb4e3172b83702940893f372589bf3d761be192070b0 00:00:00 1529
2074ca568aba33a2032f8aef363d04c50ea08fa3d4948c250781d0a16d44ce68 00:00:04 5829  | 2074ca568aba33a2032f8aef363d04c50ea08fa3d4948c250781d0a16d44ce68 00:00:01 5829
195f5a267829fc594fede0a277ebbb6bf40d2255ef4e659d4551ab5f4c524744 00:00:00 961     195f5a267829fc594fede0a277ebbb6bf40d2255ef4e659d4551ab5f4c524744 00:00:00 961
afa0bb539a4d922b9cdba5d48f7f2935b20dd4da33263adedd4d7741ef5ec8bb 00:00:08 6980  | afa0bb539a4d922b9cdba5d48f7f2935b20dd4da33263adedd4d7741ef5ec8bb 00:00:01 6980
6c4d36e72e0391613c6121e3564d13e5e3866ecd163675bbe181a7822b72d258 00:00:00 1492    6c4d36e72e0391613c6121e3564d13e5e3866ecd163675bbe181a7822b72d258 00:00:00 1492
73d96714c1b8d895429446f490f76b90f1136f697bdf24fa95d73f2b02f64c99 00:00:01 1228  | 73d96714c1b8d895429446f490f76b90f1136f697bdf24fa95d73f2b02f64c99 00:00:00 1228
75613dd4aede8b19f444db94545f924fc5ca771d26295c89d6e43c6214515f99 00:00:00 927     75613dd4aede8b19f444db94545f924fc5ca771d26295c89d6e43c6214515f99 00:00:00 927
0b2438a0415dc0bb773dbe1cc677b48cfb13fd4a34eecc1184025549a7611f8b 00:00:11 8195  | 0b2438a0415dc0bb773dbe1cc677b48cfb13fd4a34eecc1184025549a7611f8b 00:00:02 8195
f6573fcc37e486a367c2401919ce86589fc2d912c3fcd676d1060cb038b3d853 00:00:00 1631    f6573fcc37e486a367c2401919ce86589fc2d912c3fcd676d1060cb038b3d853 00:00:00 1631
19cb507bc2c0af583a462a92a87c932f7922e42475b4332615b98c524e996d2d 00:00:01 3709    19cb507bc2c0af583a462a92a87c932f7922e42475b4332615b98c524e996d2d 00:00:01 3709
14217b027836de1547f9a5f3b1f324fdaa4b7fe63655fa706b9a0c3bf3cdf848 00:00:02 3581  | 14217b027836de1547f9a5f3b1f324fdaa4b7fe63655fa706b9a0c3bf3cdf848 00:00:00 3581
08c8bf98b183742416575c361054484572fec8bde4f5ad6d541eafd9c578deca 00:00:00 550     08c8bf98b183742416575c361054484572fec8bde4f5ad6d541eafd9c578deca 00:00:00 550
48e8805952cacefa149d76b24b9ad23a765991b77b535546448c297d10840686 00:00:00 1143  | 48e8805952cacefa149d76b24b9ad23a765991b77b535546448c297d10840686 00:00:01 1143
f24a226bdf81b0a10302537bf348a6b3dbce7979486a39cb59b57dd3909aef8b 00:00:06 6232  | f24a226bdf81b0a10302537bf348a6b3dbce7979486a39cb59b57dd3909aef8b 00:00:01 6232
381d14183cae64299d5a368381e9612eec4eac3dad64ea99164811ee992c5f44 00:00:00 1539    381d14183cae64299d5a368381e9612eec4eac3dad64ea99164811ee992c5f44 00:00:00 1539
`
`

**Comment by cogito-ray** [comment]
Slowness was introduced in 3.0.2.

**Comment by cogito-ray** [comment]
I looked at the code diffs and they are substantial enough that it would take some time to dig into it.  I reverted back to 2.2.0 and figured out a different way to deal with iterator functions to loop through an array of objects. Back to speedy rendering.

**Comment by fidian** [comment]
I found an easy way to replicate this problem and #69. Use a template that has something like this

```
{{X}}
Lots of content here. Lots of content here. Lots of content here. Lots of content here.
...
```

Just copy that "Lots of content" line about a thousand times and you'll see some severe slowdowns. Using a Bash profiling tool, I was able to find what was consuming all of the time and it was a simple string replacement. Four lines similar to this one.

```
MO_CONTENT=${MO_CONTENT# }
```

I wrapped those statements in conditions to only execute the ones that are required, which helped immensely. Template processing time for my terrible example went from about 6 seconds to 0.5 seconds. I'm able to process the attached template.json in about 8 seconds instead of 30.

@JuergenMang what speeds were you expecting to see? Could you check if the new version does what you need?
