### ISSUE TITLE
Do Parents work?

### ISSUE THREAD

**Issue by WesselAtWork** [tests-always-included/mo#74]
Trying to use [partials](https://mustache.github.io/mustache.5.html#Partials) with [blocks](https://mustache.github.io/mustache.5.html#Blocks) and [parents](https://mustache.github.io/mustache.5.html#Parents)

##### partial.mo
```mustache
{{$block}}
bae
{{/block}}
```

##### template.mo
```mustache
{{<partial.mo}}
{{$block}}
bae
{{/block}}
{{/partial.mo}}
```

With `mo template.mo`

Getting Error:
```text
ERROR: Unable to index a scalar as an array: <partial.mo
```

I think it's unsupported (couldn't find anything dealing with this superficially in the bash) but just verifying

**Comment by fidian** [comment]
Because there's no scoping and no way to really dive deeper into objects in Bash, there is no support for parents. I did not call this out in the documentation and will update the README to do so.

**Comment by fidian** [comment]
Sorry, I had "parents" mixed up with another mustache implementation where you could go up to a parent object or up to the root object when a partial was scoped. This is an entirely different idea, though it is still not supported.

I might add support for it if there's significant demand, but I can't even imagine how much work that would take.

The README has been updated in b595ad2.
